### ISSUE TITLE
重新编译后Resizer的模型出错

### ISSUE THREAD

**Issue by WEGFan** [Mygod/EDGE#10]
所有Resizer的静态方块模型的高度都被加了1，例如高度为2的Resizer编译后模型的高度为2，实际上应为1。
![20150810235230](https://cloud.githubusercontent.com/assets/7558201/9176289/1b31244c-3fbd-11e5-921c-b02094a68a62.jpg)

**Comment by Mygod** [comment]
这个问题本已修复，但是我忘记编译了 lol。
