### ISSUE TITLE
Edge Tool?

### ISSUE THREAD

**Issue by deli73** [Mygod/EDGE#11]
I apologize for putting this here, it's horribly unprofessional of me, but your website is down and I was wondering if there's anywhere else I can get the EDGE tool.

**Comment by deli73** [comment]
(closed, turns out en.mygod.tk works perfectly fine)

**Comment by Mygod** [comment]
What seems to be the problem? Just checked my site and it seems that everything is operating normally.

And yes, you can get compiled binary from releases page in this repository.
