### ISSUE TITLE
New version available for Android

### ISSUE THREAD

**Issue by PaperCube** [Mygod/EDGE#13]
New Version 2.2 available for Android. See https://play.google.com/store/apps/details?id=net.mobigame.edge which no longer crashes on Android 6.0 or later devices. Seems Mobigame had made a huge change to (or completely rewritten) the code

**Comment by Mygod** [comment]
Any other obvious changes besides that?

**Comment by WEGFan** [comment]
- A prism energy bar displays below the minimap
- retry.Text = "retry " + strLevelname;

**Comment by Mygod** [comment]
Sounds great. I will check it out later.

**Comment by Mygod** [comment]
Fixed. Too lazy to do 2.20 for iOS.
