### ISSUE TITLE
There might be a update of LibTwoTribes

### ISSUE THREAD

**Issue by PaperCube** [Mygod/EDGE#14]
When I tried to search LibTwoTribes on Google, here comes the following result : https://bitbucket.org/WillKirkby/libtwotribes . The website shows that it was updated on June, 2015. But most of time in this repo was updated 2 or 3 years ago. Is that a new one?

**Comment by Mygod** [comment]
The old one is hosted on GitHub.

**Comment by Mygod** [comment]
You can find the oldest source code ever and do a diff yourself: https://github.com/Mygod/EDGE/tree/75df03576df10d9590d672a188db4d53b7d02059/EdgeTool/Core/%5BLibTwoTribes%5D
