### ISSUE TITLE
Can't decompile level

### ISSUE THREAD

**Issue by WEGFan** [Mygod/EDGE#15]
Edgetool crashes when clicking on "Browse Levels"
- Windows 7 (64 bit)
- .NET 4.5
- EDGE EX (Steam version)
![qq 20170706221941](https://user-images.githubusercontent.com/7558201/27915525-41e013c2-6299-11e7-8f13-6bb70319c213.png)
![qq 20170706222002](https://user-images.githubusercontent.com/7558201/27915527-424bf9de-6299-11e7-860d-3126b9d24055.png)

**Comment by Mygod** [comment]
检查 .NET 是否 4.5.1+。建议 4.6.1+。
