### ISSUE TITLE
是不是xaml窗口在win10上都没有彩色标题栏……

### ISSUE THREAD

**Issue by Mygod** [Mygod/EDGE#18]
Suggested by @WEGFan.

**Comment by Mygod** [comment]
![image](https://user-images.githubusercontent.com/3511321/29753690-c844b43a-8b2b-11e7-93bd-fa09f82c8cbd.png)

不是不可以，但是会很丑。（除非不使用 Windows 自带的标题）

Thanks Microsoft!

**Comment by Mygod** [comment]
See here for a test build: https://github.com/Mygod/MygodLibrary/tree/win10-accent

**Comment by WEGFan** [comment]
不丑啊……不是跟win8一样吗

**Comment by Mygod** [comment]
你仔细看看？

**Comment by WEGFan** [comment]
好吧那个阴影……不能只让标题栏有颜色吗

**Comment by Mygod** [comment]
还有一个很丑的地方。

理论上来说可能可以，但是现在做的这个效果已经是 undocumented API 了（抄了别人的研究成果），懒得进一步搞了，要是有什么可以抄抄的话我就做。
