### ISSUE TITLE
How I can create levels?

### ISSUE THREAD

**Issue by NicolasPL64** [Mygod/EDGE#19]
I have a cracked version, but I don't know how I can create a level :P

**Comment by Mygod** [comment]
Read edgefans-archive.

**Comment by WEGFan** [comment]
But it doesn't have an English version...

**Comment by Mygod** [comment]
Use Google translate and human help (like post more specific questions here).

**Comment by NicolasPL64** [comment]
I don't know how this works... >:(

**Comment by Mygod** [comment]
Okay start from [here](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fedgefans.mygod.be%2Fedgefans.tk%2Fdevelopers.html). It's machine translated so come back if you have trouble.

If there's anything you can't understand, feel free to ask. Basically to get started, you just open game folder, drag and drop files into EdgeTool and start tweaking decoded files, drag the decoded file back to encode back and start the game. If you want to know how to read decoded files, go to that link.
